fix java_home path

diff --git a/services/R-kernel/kernels/R_ohdsi_docker/Dockerfile b/services/R-kernel/kernels/R_ohdsi_docker/Dockerfile
--- a/services/R-kernel/kernels/R_ohdsi_docker/Dockerfile
+++ b/services/R-kernel/kernels/R_ohdsi_docker/Dockerfile
@@ -33,17 +33,16 @@ RUN apt-get update && \
 # RUN git config --global advice.detachedHead false
 
 # Set environment variables
-ENV JAVA_HOME_11=/usr/lib/jvm/openjdk-11
-ENV JAVA_HOME=/usr/lib/jvm/openjdk-17
+ENV JAVA_HOME=/usr/lib/jvm/openjdk-11
 ENV PATH="$JAVA_HOME/bin::/root/.cargo/bin:$PATH"
 ENV LD_LIBRARY_PATH=/usr/lib/jvm/openjdk-11/lib/server
 ENV R_REMOTES_UPGRADE="always"
 
 # OpenJDK 11
-RUN arch="$(dpkg --print-architecture)"; case "$arch" in 'amd64') downloadUrl='https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.16%2B8/OpenJDK11U-jdk_x64_linux_11.0.16_8.tar.gz'; ;; 'arm64') downloadUrl='https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.16%2B8/OpenJDK11U-jdk_aarch64_linux_11.0.16_8.tar.gz'; ;; *) echo >&2 "error: unsupported architecture: '$arch'"; exit 1 ;; esac; wget --progress=dot:giga -O openjdk.tgz "$downloadUrl"; mkdir -p ${JAVA_HOME_11}; tar --extract --file openjdk.tgz --directory "$JAVA_HOME_11" --strip-components 1 --no-same-owner ;
+RUN arch="$(dpkg --print-architecture)"; case "$arch" in 'amd64') downloadUrl='https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.16%2B8/OpenJDK11U-jdk_x64_linux_11.0.16_8.tar.gz'; ;; 'arm64') downloadUrl='https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.16%2B8/OpenJDK11U-jdk_aarch64_linux_11.0.16_8.tar.gz'; ;; *) echo >&2 "error: unsupported architecture: '$arch'"; exit 1 ;; esac; wget --progress=dot:giga -O openjdk.tgz "$downloadUrl"; mkdir -p ${JAVA_HOME}; tar --extract --file openjdk.tgz --directory "$JAVA_HOME" --strip-components 1 --no-same-owner ;
 
-RUN update-alternatives --install /usr/bin/java java ${JAVA_HOME_11}/bin/java 100 && \
-    update-alternatives --install /usr/bin/javac javac ${JAVA_HOME_11}/bin/javac 100 && \
+RUN update-alternatives --install /usr/bin/java java ${JAVA_HOME}/bin/java 100 && \
+    update-alternatives --install /usr/bin/javac javac ${JAVA_HOME}/bin/javac 100 && \
     rm openjdk.tgz*
 
 # Verify the installation
