Update dockerfiles, renv.lock and uv.lock files

diff --git a/flows/base/Dockerfile b/flows/base/Dockerfile
--- a/flows/base/Dockerfile
+++ b/flows/base/Dockerfile
@@ -1,23 +1,49 @@
 ARG PYTHON_VERSION=3.12
+ARG R_VERSION=4.4.3
 
-FROM alpine AS builder
+FROM rocker/r-ver:${R_VERSION} AS python-dependencies-build
 
-# Create .Renviron file with GITHUB_PAT
-ARG GITHUB_PAT
-RUN echo "GITHUB_PAT=$GITHUB_PAT" >> .Renviron
+RUN apt-get update && \
+    apt-get install -y --no-install-recommends \
+    cmake \
+    gcc \
+    g++ \
+    software-properties-common \
+    # To build psycopg2-binary
+    libpq-dev \
+    # To build rpy2
+    liblzma-dev \
+    libdeflate-dev \
+    libcairo2-dev \
+    libssl-dev \
+    libxml2-dev \
+    && apt-get clean --yes \
+    && rm -rf /var/lib/apt/{apt,dpkg,cache,log}/
 
-FROM python:${PYTHON_VERSION}-slim-bookworm AS python-source
-# For copying into R images
+ENV UV_LINK_MODE=copy \
+    UV_COMPILE_BYTECODE=1 \
+    # UV_PYTHON_DOWNLOADS=manual
+    # Install managed python which will be copied over to runtime build
+    UV_PYTHON_INSTALL_DIR=/app/python \
+    UV_PYTHON_PREFERENCE=only-managed
 
-FROM rocker/r-ver:4.4.1 AS python-dependencies-build
+COPY --from=ghcr.io/astral-sh/uv:0.8.4 /uv /uvx /bin/
+RUN uv python install ${PYTHON_VERSION}
 
+WORKDIR /app
 
-# RPY2 needs R to compile
+# Install dependencies with uv into a venv
+RUN --mount=type=cache,target=/root/.cache/uv \
+    --mount=type=bind,source=./base/uv.lock,target=uv.lock \
+    --mount=type=bind,source=./base/pyproject.toml,target=pyproject.toml \
+    uv sync --frozen --no-install-project --no-dev --no-editable
+    
+    # To check on installation of rpy2:
+    # uv sync --all-groups
+    # ENV PATH="/app/.venv/bin:$PATH"
+    # pytest --pyargs 'rpy2.tests'
 
-ENV PYTHON_ROOT=/opt/python
-ENV VENV_PATH=/app/venv
-ENV PATH="${VENV_PATH}/bin:${PYTHON_ROOT}/bin:$PATH"
-
+FROM rocker/r-ver:${R_VERSION} AS r-dependencies-build
 
 RUN apt-get update && \
     apt-get install -y --no-install-recommends \
@@ -41,6 +67,7 @@ RUN apt-get update && \
     libjpeg-dev \
     libpng-dev \
     libpq-dev \
+    libpq5 \
     libprotobuf-dev \
     libsodium23 libsodium-dev libsecret-tools \
     libssh2-1-dev \
@@ -52,50 +79,58 @@ RUN apt-get update && \
     openssh-client \
     protobuf-compiler \
     software-properties-common \
-    sqlite3 \
     vim-tiny \
     wget \
-    && rm -rf /var/lib/apt/lists/* \
-    && apt-get clean
+    && apt-get clean --yes \
+    && rm -rf /var/lib/apt/{apt,dpkg,cache,log}/
 
-# Copy Python 3.12 binary, libs, and site-packages from the python image
-COPY --from=python-source /usr/local /opt/python
+# Set environment variables
+ENV JAVA_HOME=/usr/lib/jvm/openjdk-17
+ENV PATH="$JAVA_HOME/bin::/root/.cargo/bin:$PATH"
+ENV LD_LIBRARY_PATH=/usr/lib/jvm/openjdk-17/lib/server
+ENV R_REMOTES_UPGRADE="always"
+
+ENV APP_VERSION=0.0.0
+ENV PRING_PROFILES_ACTIVE=prod   
 
 
-COPY --from=ghcr.io/astral-sh/uv:0.8.4 /uv /uvx /bin/
+RUN set -e; \
+    mkdir -p -m 700 ~/.ssh && \
+    # GitHub setup & test
+    ssh-keyscan github.com | tee -a ~/.ssh/known_hosts && \
+    git ls-remote https://github.com/data2evidence/d2e-DatabaseConnector.git | grep HEAD && \
+    git ls-remote https://github.com/data2evidence/d2e-SqlRender.git | grep HEAD && \
+    git config --global advice.detachedHead false && \
+    # Install OpenJDK 17
+    arch="$(dpkg --print-architecture)" && \
+    case "$arch" in \
+      'amd64') downloadUrl='https://github.com/AdoptOpenJDK/openjdk17-binaries/releases/download/jdk-2021-05-07-13-31/OpenJDK-jdk_x64_linux_hotspot_2021-05-06-23-30.tar.gz' ;; \
+      'arm64') downloadUrl='https://github.com/AdoptOpenJDK/openjdk17-binaries/releases/download/jdk-2021-05-07-13-31/OpenJDK-jdk_aarch64_linux_hotspot_2021-05-06-23-30.tar.gz' ;; \
+      *) echo >&2 "error: unsupported architecture: '$arch'"; exit 1 ;; \
+    esac && \
+    wget --progress=dot:giga -O openjdk.tgz "$downloadUrl" && \
+    mkdir -p ${JAVA_HOME} && \
+    tar --extract --file openjdk.tgz --directory "$JAVA_HOME" --strip-components 1 --no-same-owner && \
+    rm openjdk.tgz*
 
 
-ENV UV_LINK_MODE=copy \
-    UV_COMPILE_BYTECODE=1 \
-    UV_PYTHON_DOWNLOADS=never
-
-# Install dependencies with uv into /app/venv
 WORKDIR /app
 
-RUN --mount=type=cache,target=/root/.cache/uv \
-    --mount=type=bind,source=./base/uv.lock,target=uv.lock \
-    --mount=type=bind,source=./base/pyproject.toml,target=pyproject.toml \
-    uv sync --locked --no-install-project --no-editable --no-dev
+COPY ./base/renv.lock ./build/.Rprofile ./build/install_and_verify_r_packages.R /app/
 
+# Install R depdendencies in global library
+ARG REQUIRED_R_PACKAGES="Achilles DataQualityDashboard CommonDataModel DatabaseConnector SqlRender"
+RUN chmod +x /app/install_and_verify_r_packages.R && \
+    /app/install_and_verify_r_packages.R "$REQUIRED_R_PACKAGES" && \
+    R CMD javareconf && \
+    rm -f /app/renv.lock /app/.Rprofile /app/install_and_verify_r_packages.R
 
-FROM rocker/r-ver:4.4.1 AS r-dependencies-build
+FROM r-dependencies-build AS runtime
 
+ARG DUCKDB_VERSION=1.2.1
+ARG DUCKDB_EXTENSIONS="postgres_scanner,fts"
 
-WORKDIR /app
-# GITHUB_PAT authentication for OHDSI remotes::install_github
-COPY --from=builder .Renviron .
-
-# GitHub deploy key ssh-config authentication for OHDSI remotes::install_github. host ssh-agent supplies private keys
-# COPY .github /root/
-
-RUN apt-get update && \
-    apt-get install -y --no-install-recommends \
-    ca-certificates \
-    cmake \
-    dirmngr \
-    ed \
-    git \
-    less \
+RUN apt-get purge -y \
     libbz2-dev \
     libcairo2-dev \
     libcurl4-gnutls-dev \
@@ -109,127 +144,65 @@ RUN apt-get update && \
     libpng-dev \
     libpq-dev \
     libprotobuf-dev \
-    libsodium23 libsodium-dev libsecret-tools \
+    libsodium-dev \
     libssh2-1-dev \
     libssl-dev \
     libtiff-dev \
     libxml2-dev \
     libxt-dev \
-    locales \
-    openssh-client \
-    protobuf-compiler \
-    software-properties-common \
-    sqlite3 \
-    vim-tiny \
-    wget \
-    && rm -rf /var/lib/apt/lists/* \
-    && apt-get clean
-
-# GitHub setup & test
-RUN mkdir -p -m 700 ~/.ssh/ && ssh-keyscan github.com | tee -a ~/.ssh/known_hosts
-# RUN ssh-add -l # debug only
-RUN git ls-remote https://github.com/data2evidence/d2e-DatabaseConnector.git | grep HEAD || exit 1
-RUN git ls-remote https://github.com/data2evidence/d2e-SqlRender.git | grep HEAD || exit 1
-RUN git config --global advice.detachedHead false
-
-ENV PATH="/usr/src/app/bin:$PATH"
-
-# Set environment variables
-ENV JAVA_HOME=/usr/lib/jvm/openjdk-17
-ENV PATH="$JAVA_HOME/bin::/root/.cargo/bin:$PATH"
-ENV LD_LIBRARY_PATH=/usr/lib/jvm/openjdk-17/lib/server
-ENV APP_VERSION=0.0.0
-ENV PRING_PROFILES_ACTIVE=prod
-
-# OpenJDK 17
-RUN arch="$(dpkg --print-architecture)"; case "$arch" in 'amd64') downloadUrl='https://github.com/AdoptOpenJDK/openjdk17-binaries/releases/download/jdk-2021-05-07-13-31/OpenJDK-jdk_x64_linux_hotspot_2021-05-06-23-30.tar.gz'; ;; 'arm64') downloadUrl='https://github.com/AdoptOpenJDK/openjdk17-binaries/releases/download/jdk-2021-05-07-13-31/OpenJDK-jdk_aarch64_linux_hotspot_2021-05-06-23-30.tar.gz'; ;; *) echo >&2 "error: unsupported architecture: '$arch'"; exit 1 ;; esac; wget --progress=dot:giga -O openjdk.tgz "$downloadUrl"; mkdir -p ${JAVA_HOME}; tar --extract --file openjdk.tgz --directory "$JAVA_HOME" --strip-components 1 --no-same-owner ;
-
-RUN rm openjdk.tgz*
-
-# Verify the installation
-RUN java -version && R CMD javareconf
-
-COPY ./base/renv.lock renv.lock
-COPY ./base/.Rprofile .Rprofile
-
-# Install in global library
-RUN Rscript -e 'install.packages("remotes", repos = "https://cloud.r-project.org"); \
-                remotes::install_version("renv", version = "1.1.4", repos = "https://cloud.r-project.org"); \
-                Sys.setenv(RENV_CONFIG_SANDBOX_ENABLED = FALSE); \
-                Sys.setenv(RENV_PATHS_LIBRARY = "/usr/local/lib/R/site-library"); \ 
-                .libPaths("/usr/local/lib/R/site-library"); \
-                renv::restore(lockfile = "/app/renv.lock",library = "/usr/local/lib/R/site-library",prompt = FALSE)'
-
-# Verify installation and fail if any are missing
-RUN Rscript -e "required <- c('Achilles', 'DataQualityDashboard', 'CommonDataModel', 'DatabaseConnector', 'SqlRender'); \
-                installed <- rownames(installed.packages()); \
-                missing <- setdiff(required, installed); \
-                if (length(missing) > 0) { \
-                    stop(paste('Missing packages:', paste(missing, collapse = ', '))) \
-                }"
-
-FROM r-dependencies-build AS runtime
+    g++ \
+    gcc \
+    cmake \
+    && apt-get autoremove -y \
+    && apt-get clean --yes \
+    && rm -rf /var/lib/apt/{apt,dpkg,cache,log}/ \
+    # Create user and group for ownership
+    && useradd docker -u 1001 \
+    && groupadd alp \
+    && mkdir /home/docker \
+    && chown docker:docker /home/docker \
+    && adduser docker staff \
+    && adduser docker alp
 
 
-ARG BUILD_TYPE
-ARG USER=docker
-ENV USER=${USER}
-ARG UID=1000
-ARG GID=1000
-RUN groupadd -g $GID ${USER}
-RUN useradd -m -d /home/${USER} -s /bin/bash -g ${USER} -u ${UID} ${USER}
+COPY ./build/download_duckdb_extensions.sh /app/download_duckdb_extensions.sh
+
+RUN \
+    # Create output directory and set ownership
+    mkdir -p /output \
+    && chown -R docker:docker /output \
+    # Create directory for DuckDB extensions
+    && mkdir -p /app/duckdb_extensions \
+    && chmod -R 755 /app/duckdb_extensions \
+    # Make the download script executable
+    && chmod +x /app/download_duckdb_extensions.sh \
+    # Install DuckDB extensions in the duckdb_extensions directory
+    && cd /app/duckdb_extensions \
+    && /app/download_duckdb_extensions.sh "$DUCKDB_VERSION" "$DUCKDB_EXTENSIONS" \
+    && rm -f /app/download_duckdb_extensions.sh
 
 
-RUN apt-get update && \
-    apt-get install -y --no-install-recommends \
-    libpq5 \
-    libpq-dev \
-    && rm -rf /var/lib/apt/lists/* \
-    && apt-get clean
+COPY --chown=docker:docker  ./__init__.py /app/
+COPY --chown=docker:docker ./_shared_flow_utils/drivers /app/inst/drivers/
 
+# Copy the Python virtual environment and uv binary from the build stage
+COPY --from=python-dependencies-build --chown=docker:docker /bin/uv /usr/local/bin/uv
+COPY --from=python-dependencies-build --chown=docker:docker /app/python /app/python
+COPY --from=python-dependencies-build --chown=docker:docker /app/.venv /app/.venv
 
-# Copy Python 3.12 binary, libs, and site-packages from the python image
-COPY --from=python-source /usr/local /opt/python
+# For post installs during runtime
+COPY --chown=docker:docker ./base/pyproject.toml ./base/uv.lock /app/
 
+# Application files
+COPY --chown=docker:docker --chmod=711 ./_shared_flow_utils /app/_shared_flow_utils
+COPY --chown=docker:docker --chmod=711 ./base/*_plugin /app/flows/
 
-RUN mkdir /output
-RUN chown -R docker:docker /output
-
-WORKDIR /app
-
-COPY --from=python-dependencies-build --chown=app:app /app/.venv /app/.venv
-
-# Create folder to store duckdb extensions for offline plugins
-# Version must match duckdb in pyproject.toml
-ENV duckdb_version=1.2.1
-RUN mkdir -p /app/duckdb_extensions
-WORKDIR /app/duckdb_extensions
-RUN wget https://extensions.duckdb.org/v${duckdb_version}/linux_amd64_gcc4/postgres_scanner.duckdb_extension.gz \
-    && wget https://extensions.duckdb.org/v${duckdb_version}/linux_amd64_gcc4/fts.duckdb_extension.gz \
-    && gzip -d postgres_scanner.duckdb_extension.gz \
-    && gzip -d fts.duckdb_extension.gz
-
-# Create folder for duckdb database files
-RUN mkdir ./duckdb_data
-RUN chown docker:docker ./duckdb_data
-RUN mkdir -p ./cdw-config/duckdb_data
-RUN chown -R docker:docker ./cdw-config
-
-WORKDIR /app
-
-COPY --chown=docker:docker ./_shared_flow_utils/postgresql-42.3.1.jar ./inst/drivers/
-COPY --chown=docker:docker ./_shared_flow_utils/ngdbc-latest.jar ./inst/drivers/
-COPY --chown=docker:docker  ./__init__.py .
-COPY --chown=docker:docker --chmod=711 ./_shared_flow_utils _shared_flow_utils
-COPY --chown=docker:docker --chmod=711 ./base flows
-
-# Grant docker user read/write access
 RUN chmod -R 755 /app
 
-RUN rm -rf .Renviron /app/.github/.ssh
-
-ENV PATH="/app/.venv/bin:$PATH"
-
 WORKDIR /app
+
+# Place executables in the environment at the front of the path
+ENV PATH="/app/.venv/bin:$PATH"
+ENV INSTALL_SQLALCHEMY_FLAG=true
 
 USER docker
diff --git a/flows/data_management/Dockerfile b/flows/data_management/Dockerfile
--- a/flows/data_management/Dockerfile
+++ b/flows/data_management/Dockerfile
@@ -1,6 +1,6 @@
 ARG PYTHON_VERSION=3.12
 
-FROM python:${PYTHON_VERSION}-slim AS base-build
+FROM python:${PYTHON_VERSION}-slim AS python-dependencies-build
 
 RUN apt-get update && \
     apt-get install -y --no-install-recommends \
@@ -8,16 +8,16 @@ RUN apt-get update && \
     gcc \
     g++ \
     libpq-dev \
-    && rm -rf /var/lib/apt/lists/* \
-    && apt-get clean
-
-COPY --from=ghcr.io/astral-sh/uv:0.8.4 /uv /uvx /bin/
-
-WORKDIR /app
+    && apt-get clean --yes \
+    && rm -rf /var/lib/apt/{apt,dpkg,cache,log}/
 
 ENV UV_LINK_MODE=copy \
     UV_COMPILE_BYTECODE=1 \
     UV_PYTHON_DOWNLOADS=never
+
+COPY --from=ghcr.io/astral-sh/uv:0.8.4 /uv /uvx /bin/
+
+WORKDIR /app
 
 # Install dependencies with uv into a venv
 RUN --mount=type=cache,target=/root/.cache/uv \
@@ -28,7 +28,6 @@ RUN --mount=type=cache,target=/root/.cache/uv \
 
 FROM python:${PYTHON_VERSION}-slim AS runtime
 
-ARG BUILD_TYPE
 ARG USER=docker
 ENV USER=${USER}
 ARG UID=1000
@@ -36,49 +35,53 @@ ARG GID=1000
 RUN groupadd -g $GID ${USER}
 RUN useradd -m -d /home/${USER} -s /bin/bash -g ${USER} -u ${UID} ${USER}
 
-WORKDIR /app
-
 RUN apt-get update && \
     apt-get install -y --no-install-recommends \
+    curl \
     wget \
     openjdk-17-jdk\
     libpq5 \
-    && rm -rf /var/lib/apt/lists/* \
-    && apt-get clean
+    && apt-get clean --yes \
+    && rm -rf /var/lib/apt/{apt,dpkg,cache,log}/
 
 
 # Set environment variables
-ENV JAVA_HOME=/usr/lib/jvm/openjdk-11
+ENV JAVA_HOME=/usr/lib/jvm/openjdk-17
 ENV PATH="$JAVA_HOME/bin::/root/.cargo/bin:$PATH"
-ENV LD_LIBRARY_PATH=/usr/lib/jvm/openjdk-11/lib/server
+ENV LD_LIBRARY_PATH=/usr/lib/jvm/openjdk-17/lib/server
 
 # OpenJDK 17
-RUN arch="$(dpkg --print-architecture)"; case "$arch" in 'amd64') downloadUrl='https://github.com/AdoptOpenJDK/openjdk17-binaries/releases/download/jdk-2021-05-07-13-31/OpenJDK-jdk_x64_linux_hotspot_2021-05-06-23-30.tar.gz'; ;; 'arm64') downloadUrl='https://github.com/AdoptOpenJDK/openjdk17-binaries/releases/download/jdk-2021-05-07-13-31/OpenJDK-jdk_aarch64_linux_hotspot_2021-05-06-23-30.tar.gz'; ;; *) echo >&2 "error: unsupported architecture: '$arch'"; exit 1 ;; esac; wget --progress=dot:giga -O openjdk.tgz "$downloadUrl"; mkdir -p ${JAVA_HOME}; tar --extract --file openjdk.tgz --directory "$JAVA_HOME" --strip-components 1 --no-same-owner ;
+# RUN arch="$(dpkg --print-architecture)"; case "$arch" in 'amd64') downloadUrl='https://github.com/AdoptOpenJDK/openjdk17-binaries/releases/download/jdk-2021-05-07-13-31/OpenJDK-jdk_x64_linux_hotspot_2021-05-06-23-30.tar.gz'; ;; 'arm64') downloadUrl='https://github.com/AdoptOpenJDK/openjdk17-binaries/releases/download/jdk-2021-05-07-13-31/OpenJDK-jdk_aarch64_linux_hotspot_2021-05-06-23-30.tar.gz'; ;; *) echo >&2 "error: unsupported architecture: '$arch'"; exit 1 ;; esac; wget --progress=dot:giga -O openjdk.tgz "$downloadUrl"; mkdir -p ${JAVA_HOME}; tar --extract --file openjdk.tgz --directory "$JAVA_HOME" --strip-components 1 --no-same-owner ;
+# RUN rm openjdk.tgz*
 
-RUN rm openjdk.tgz*
-
-COPY --chown=docker:docker ./_shared_flow_utils/postgresql-42.3.1.jar ./inst/drivers/
-# COPY --chown=docker:docker ./_shared_flow_utils/ngdbc-latest.jar ./inst/drivers/
-COPY --chown=docker:docker ./__init__.py .
-
+WORKDIR /app
 ADD https://github.com/liquibase/liquibase/releases/download/v4.5.0/liquibase-4.5.0.tar.gz .
-RUN mkdir -p ./liquibase/
-RUN tar xvf liquibase-4.5.0.tar.gz -C ./liquibase/ && rm liquibase-4.5.0.tar.gz
+RUN mkdir -p ./liquibase/ \
+    && tar xvf liquibase-4.5.0.tar.gz -C ./liquibase/ \
+    && rm liquibase-4.5.0.tar.gz \
+    && chown -R docker:docker ./liquibase/
 
-# Grant docker ownership to create properties file
-RUN chown -R docker:docker ./liquibase/
+WORKDIR /app
+COPY --chown=docker:docker  ./__init__.py /app/
+COPY --chown=docker:docker ./_shared_flow_utils/drivers /app/inst/drivers/
 
-COPY --from=base-build --chown=app:app /app/.venv /app/.venv
+# Copy the Python virtual environment and uv binary from the build stage
+COPY --from=python-dependencies-build --chown=docker:docker /bin/uv /usr/local/bin/uv
+COPY --from=python-dependencies-build --chown=docker:docker /app/.venv /app/.venv
 
-COPY --chown=docker:docker ./_shared_flow_utils/postgresql-42.3.1.jar ./inst/drivers/
-COPY --chown=docker:docker ./__init__.py .
+# For post installs during runtime
+COPY --chown=docker:docker ./base/pyproject.toml ./base/uv.lock /app/
 
-COPY --chown=docker:docker --chmod=711 ./_shared_flow_utils _shared_flow_utils
-COPY --chown=docker:docker --chmod=711 ./data_management/data_management_plugin flows/data_management_plugin
+# Application files
+COPY --chown=docker:docker --chmod=711 ./_shared_flow_utils /app/_shared_flow_utils
+COPY --chown=docker:docker --chmod=711 ./data_management/*_plugin /app/flows/
 
-# Grant docker user read/write access
 RUN chmod -R 755 /app
 
+WORKDIR /app
+
+# Place executables in the environment at the front of the path
 ENV PATH="/app/.venv/bin:$PATH"
+ENV INSTALL_SQLALCHEMY_FLAG=true
 
 USER docker
diff --git a/flows/hades/Dockerfile b/flows/hades/Dockerfile
--- a/flows/hades/Dockerfile
+++ b/flows/hades/Dockerfile
@@ -1,17 +1,94 @@
+ARG PYTHON_VERSION=3.12
+ARG R_VERSION=4.4.3
+
 FROM alpine AS builder
 
 # Create .Renviron file with GITHUB_PAT
 ARG GITHUB_PAT
 RUN echo "GITHUB_PAT=$GITHUB_PAT" >> .Renviron
 
-FROM rocker/r-ver:4.4 AS base-build
+FROM rocker/r-ver:${R_VERSION} AS python-dependencies-build
 
-USER root
-RUN mkdir -p /app
+RUN apt-get update && \
+    apt-get install -y --no-install-recommends \
+    cmake \
+    gcc \
+    g++ \
+    software-properties-common \
+    # To build psycopg2-binary
+    libpq-dev \
+    # To build rpy2
+    liblzma-dev \
+    libdeflate-dev \
+    libcairo2-dev \
+    libssl-dev \
+    libxml2-dev \
+    && apt-get clean --yes \
+    && rm -rf /var/lib/apt/{apt,dpkg,cache,log}/
+
+# RUN apt-get update && \
+#     apt-get install -y --no-install-recommends \
+#     ca-certificates \
+#     cmake \
+#     curl \
+#     dirmngr \
+#     ed \
+#     gcc \
+#     git \
+#     less \
+#     libbz2-dev \
+#     libcairo2-dev \
+#     libcurl4-gnutls-dev \
+#     libfontconfig1-dev \
+#     libfreetype6-dev \
+#     libfribidi-dev \
+#     libgit2-dev \
+#     libharfbuzz-dev \
+#     libicu-dev \
+#     libjpeg-dev \
+#     libpng-dev \
+#     libpq-dev \
+#     libprotobuf-dev \
+#     libsodium23 libsodium-dev libsecret-tools \
+#     libssh2-1-dev \
+#     libssl-dev \
+#     libtiff-dev \
+#     libxml2-dev \
+#     libxt-dev \
+#     locales \
+#     openssh-client \
+#     protobuf-compiler \
+#     software-properties-common \
+#     sqlite3 \
+#     vim-tiny \
+#     wget \
+#     && rm -rf /var/lib/apt/lists/* \
+#     && apt-get clean
+
+ENV UV_LINK_MODE=copy \
+    UV_COMPILE_BYTECODE=1 \
+    # UV_PYTHON_DOWNLOADS=manual
+    # Install managed python which will be copied over to runtime build
+    UV_PYTHON_INSTALL_DIR=/app/python \
+    UV_PYTHON_PREFERENCE=only-managed
+
+COPY --from=ghcr.io/astral-sh/uv:0.8.4 /uv /uvx /bin/
+RUN uv python install ${PYTHON_VERSION}
 
 WORKDIR /app
-# GITHUB_PAT authentication for OHDSI remotes::install_github
-COPY --from=builder .Renviron .
+
+# Install dependencies with uv into a venv
+RUN --mount=type=cache,target=/root/.cache/uv \
+    --mount=type=bind,source=./hades/uv.lock,target=uv.lock \
+    --mount=type=bind,source=./hades/pyproject.toml,target=pyproject.toml \
+    uv sync --frozen --no-install-project --no-dev --no-editable
+
+    # To check on installation of rpy2:
+    # uv sync --all-groups
+    # ENV PATH="/app/.venv/bin:$PATH"
+    # pytest --pyargs 'rpy2.tests'
+
+FROM rocker/r-ver:${R_VERSION} AS r-dependencies-build
 
 RUN apt-get update && \
     apt-get install -y --no-install-recommends \
@@ -33,8 +110,10 @@ RUN apt-get update && \
     libharfbuzz-dev \
     libicu-dev \
     libjpeg-dev \
+    libglpk-dev \
     libpng-dev \
     libpq-dev \
+    libpq5 \
     libprotobuf-dev \
     libsodium23 libsodium-dev libsecret-tools \
     libssh2-1-dev \
@@ -45,96 +124,111 @@ RUN apt-get update && \
     locales \
     openssh-client \
     protobuf-compiler \
-    python3 \
-    python3-dev \
-    python3-pip \
-    python3-venv \
     software-properties-common \
-    sqlite3 \
     vim-tiny \
+    libnode-dev \
+    xz-utils \
     wget \
+    && rm -rf /var/lib/apt/lists/* \
     && apt-get clean
 
-# Python Library Setup
-RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 20
-RUN python3 -m venv /usr/src/app
-# Enable venv
-ENV PATH="/usr/src/app/bin:$PATH"
+WORKDIR /app
 
+COPY --from=builder .Renviron .
+
+# Set environment variables
 ENV JAVA_HOME=/usr/lib/jvm/openjdk-11
 ENV PATH="$JAVA_HOME/bin::/root/.cargo/bin:$PATH"
 ENV LD_LIBRARY_PATH=/usr/lib/jvm/openjdk-11/lib/server
 ENV R_REMOTES_UPGRADE="always"
 
-# OpenJDK 11
-RUN arch="$(dpkg --print-architecture)"; case "$arch" in 'amd64') downloadUrl='https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.16%2B8/OpenJDK11U-jdk_x64_linux_11.0.16_8.tar.gz'; ;; 'arm64') downloadUrl='https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.16%2B8/OpenJDK11U-jdk_aarch64_linux_11.0.16_8.tar.gz'; ;; *) echo >&2 "error: unsupported architecture: '$arch'"; exit 1 ;; esac; wget --progress=dot:giga -O openjdk.tgz "$downloadUrl"; mkdir -p ${JAVA_HOME}; tar --extract --file openjdk.tgz --directory "$JAVA_HOME" --strip-components 1 --no-same-owner ;
 
-RUN update-alternatives --install /usr/bin/java java ${JAVA_HOME}/bin/java 100 && \
-    update-alternatives --install /usr/bin/javac javac ${JAVA_HOME}/bin/javac 100 && \
+RUN arch="$(dpkg --print-architecture)"; \
+    case "$arch" in \
+      'amd64') downloadUrl='https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.16%2B8/OpenJDK11U-jdk_x64_linux_11.0.16_8.tar.gz'; ;; \
+      'arm64') downloadUrl='https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.16%2B8/OpenJDK11U-jdk_aarch64_linux_11.0.16_8.tar.gz'; ;; \
+      *) echo >&2 "error: unsupported architecture: '$arch'"; exit 1 ;; \
+    esac; \
+    wget --progress=dot:giga -O openjdk.tgz "$downloadUrl"; \
+    mkdir -p ${JAVA_HOME}; \
+    tar --extract --file openjdk.tgz --directory "$JAVA_HOME" --strip-components 1 --no-same-owner; \
+    update-alternatives --install /usr/bin/java java ${JAVA_HOME}/bin/java 100; \
+    update-alternatives --install /usr/bin/javac javac ${JAVA_HOME}/bin/javac 100; \
     rm openjdk.tgz*
 
-# Verify the installation
-RUN java -version && R CMD javareconf
+WORKDIR /app
 
-# Install Dependencies
-RUN Rscript -e 'options(install.packages.compile.from.source = "never")'
-RUN Rscript -e 'install.packages(c("remotes", "devtools", "rJava", "usethis"), repos="https://cran.r-project.org")'
+COPY --from=builder .Renviron .
 
-# HADES Dependencies
-# https://github.com/r-lib/remotes https://search.r-project.org/CRAN/refmans/remotes/html/install_git.html
-RUN Rscript -e 'remotes::install_github("OHDSI/Andromeda@v1.0.0")' # https://github.com/OHDSI/Andromeda
-RUN Rscript -e 'remotes::install_github("OHDSI/BrokenAdaptiveRidge@v1.0.0")' # https://github.com/OHDSI/BrokenAdaptiveRidge
-RUN Rscript -e 'remotes::install_github("OHDSI/Cyclops@v3.5.1")' # https://github.com/OHDSI/Cyclops
-RUN Rscript -e 'remotes::install_github("rstudio/reticulate@v1.35.0")' # https://github.com/rstudio/reticulate
+COPY ./hades/renv.lock ./build/.Rprofile ./build/install_and_verify_r_packages.R /app/
 
-# OHDSI HADES
-# private d2e repo auth - ssh key
-# public HADES repo auth - .Renviron:GITHUB_PAT - https://ohdsi.github.io/Hades/rSetup.html#GitHub_Personal_Access_Token
-RUN Rscript -e 'remotes::install_github("OHDSI/Hades@v1.18.0")' # https://github.com/OHDSI/Hades https://ohdsi.github.io/Hades/installingHades.html
-RUN Rscript -e 'remotes::install_github("OHDSI/CirceR@v1.1.1", upgrade="never")'
-RUN Rscript -e 'remotes::install_github("OHDSI/CohortGenerator@v0.11.2", upgrade="never")'
-RUN Rscript -e 'remotes::install_github("OHDSI/CohortIncidence@v4.0.0")'
+# Install R depdendencies in global library
+ARG REQUIRED_R_PACKAGES="Hades CohortGenerator CohortIncidence Strategus Characterization CirceR CohortDiagnostics CohortIncidence CohortMethod FeatureExtraction PatientLevelPrediction SelfControlledCaseSeries DatabaseConnector"
+RUN chmod +x /app/install_and_verify_r_packages.R && \
+    /app/install_and_verify_r_packages.R "$REQUIRED_R_PACKAGES" && \
+    R CMD javareconf && \
+    rm -f /app/renv.lock /app/.Rprofile /app/install_and_verify_r_packages.R
 
-RUN Rscript -e 'remotes::install_github("OHDSI/Strategus@v1.3.0", upgrade = "never")' # Requires latest DatabaseConnector https://github.com/OHDSI/Strategus
+RUN rm -f .Renviron
 
-# OHDSI packages and versions - final
-RUN Rscript -e 'as.data.frame(installed.packages())[,c("Package", "Version")]' | awk '{print $1,$NF}' | grep -E "$(grep -l -i ohdsi /usr/local/lib/R/site-library/*/DESCRIPTION | awk -F/ '{print $(NF-1)}' | paste -sd '|')"
+FROM r-dependencies-build AS runtime
 
-# Verify installation and fail if any are missing
-RUN Rscript -e "required <- c('Hades', 'CohortGenerator', 'CohortIncidence', 'Strategus', 'Characterization', 'CirceR', 'CohortDiagnostics', 'CohortIncidence', 'CohortMethod', 'FeatureExtraction', 'PatientLevelPrediction', 'SelfControlledCaseSeries', 'DatabaseConnector'); \
-                installed <- rownames(installed.packages()); \
-                missing <- setdiff(required, installed); \
-                if (length(missing) > 0) { \
-                    stop(paste('Missing packages:', paste(missing, collapse = ', '))) \
-                }"
 
-RUN useradd docker -u 1001 \
+RUN apt-get purge -y \
+    libbz2-dev \
+    libcairo2-dev \
+    libcurl4-gnutls-dev \
+    libfontconfig1-dev \
+    libfreetype6-dev \
+    libfribidi-dev \
+    libgit2-dev \
+    libharfbuzz-dev \
+    libicu-dev \
+    libjpeg-dev \
+    libpng-dev \
+    libpq-dev \
+    libprotobuf-dev \
+    libsodium-dev \
+    libssh2-1-dev \
+    libssl-dev \
+    libtiff-dev \
+    libxml2-dev \
+    libxt-dev \
+    libnode-dev \
+    g++ \
+    gcc \
+    cmake \
+    liblzma-dev \
+    libdeflate-dev \
+    && apt-get autoremove -y \
+    && apt-get clean --yes \
+    && rm -rf /var/lib/apt/{apt,dpkg,cache,log}/ \
+    # Create user and group for ownership
+    && useradd docker -u 1001 \
     && groupadd alp \
     && mkdir /home/docker \
     && chown docker:docker /home/docker \
     && adduser docker staff \
     && adduser docker alp
 
-FROM base-build AS final-build
-ARG BUILD_TYPE
+
+COPY --chown=docker:docker  ./__init__.py /app/
+COPY --chown=docker:docker ./_shared_flow_utils/drivers /app/inst/drivers/
+
+# Copy the Python virtual environment and uv binary from the build stage
+COPY --from=python-dependencies-build --chown=docker:docker /app/python /app/python
+COPY --from=python-dependencies-build --chown=docker:docker /app/.venv /app/.venv
+
+# Application files
+COPY --chown=docker:docker --chmod=711 ./_shared_flow_utils /app/_shared_flow_utils
+COPY --chown=docker:docker --chmod=711 ./hades/*_plugin /app/flows
+
+RUN chmod -R 755 /app
+
 WORKDIR /app
 
-COPY --chown=docker:docker ./_shared_flow_utils/postgresql-42.3.1.jar ./inst/drivers/
-COPY --chown=docker:docker  ./__init__.py .
-
-COPY --chown=docker:docker --chmod=711 ./hades/requirements_hades.txt .
-ENV RUN_TYPE=$BUILD_TYPE
-RUN if [ $BUILD_TYPE = 'OSS' ]; then sed -i '/sqlalchemy-hana/d' /app/requirements*.txt; fi
-RUN pip install -r requirements_hades.txt
-
-COPY --chown=docker:docker --chmod=711 ./_shared_flow_utils _shared_flow_utils
-COPY --chown=docker:docker --chmod=711 ./hades flows
-
-RUN rm -f .Renviron
-
-# Change the ownership of /app folder to docker user for CohortGen error logs 
-RUN chown -R docker:docker /app
-# Grant docker user read/write access
-RUN chmod -R 755 /app
+# Place executables in the environment at the front of the path
+ENV PATH="/app/.venv/bin:$PATH"
+ENV INSTALL_SQLALCHEMY_FLAG=false
 
 USER docker
diff --git a/flows/i2b2/Dockerfile b/flows/i2b2/Dockerfile
--- a/flows/i2b2/Dockerfile
+++ b/flows/i2b2/Dockerfile
@@ -1,6 +1,6 @@
 ARG PYTHON_VERSION=3.12
 
-FROM python:${PYTHON_VERSION}-slim AS base-build
+FROM python:${PYTHON_VERSION}-slim AS python-dependencies-build
 
 RUN apt-get update && \
     apt-get install -y --no-install-recommends \
@@ -8,16 +8,16 @@ RUN apt-get update && \
     gcc \
     g++ \
     libpq-dev \
-    && rm -rf /var/lib/apt/lists/* \
-    && apt-get clean
-
-COPY --from=ghcr.io/astral-sh/uv:0.8.4 /uv /uvx /bin/
-
-WORKDIR /app
+    && apt-get clean --yes \
+    && rm -rf /var/lib/apt/{apt,dpkg,cache,log}/
 
 ENV UV_LINK_MODE=copy \
     UV_COMPILE_BYTECODE=1 \
     UV_PYTHON_DOWNLOADS=never
+
+COPY --from=ghcr.io/astral-sh/uv:0.8.4 /uv /uvx /bin/
+
+WORKDIR /app
 
 # Install dependencies with uv into a venv
 RUN --mount=type=cache,target=/root/.cache/uv \
@@ -25,7 +25,7 @@ RUN --mount=type=cache,target=/root/.cache/uv \
     --mount=type=bind,source=./i2b2/pyproject.toml,target=pyproject.toml \
     uv sync --locked --no-install-project --no-editable --no-dev
 
-FROM alpine AS source-code-build
+FROM alpine AS i2b2-source
 
 RUN apk add --no-cache \
     wget
@@ -40,7 +40,7 @@ RUN tar -xzf v$GITHUB_TAG.tar.gz
 
 FROM python:${PYTHON_VERSION}-slim AS runtime
 
-ARG BUILD_TYPE
+
 ARG USER=docker
 ENV USER=${USER}
 ARG UID=1000
@@ -51,7 +51,7 @@ RUN useradd -m -d /home/${USER} -s /bin/bash -g ${USER} -u ${UID} ${USER}
 RUN apt-get update && \
     apt-get install -y --no-install-recommends \
     wget \
-    # openjdk-17-jdk\
+    openjdk-17-jdk\
     libpq5 \
     && rm -rf /var/lib/apt/lists/* \
     && apt-get clean
@@ -61,13 +61,14 @@ ENV PATH="$JAVA_HOME/bin::/root/.cargo/bin:$PATH"
 ENV APP_VERSION=0.0.0
 ENV PRING_PROFILES_ACTIVE=prod
 
-# OpenJDK 17
-RUN arch="$(dpkg --print-architecture)"; case "$arch" in 'amd64') downloadUrl='https://github.com/AdoptOpenJDK/openjdk17-binaries/releases/download/jdk-2021-05-07-13-31/OpenJDK-jdk_x64_linux_hotspot_2021-05-06-23-30.tar.gz'; ;; 'arm64') downloadUrl='https://github.com/AdoptOpenJDK/openjdk17-binaries/releases/download/jdk-2021-05-07-13-31/OpenJDK-jdk_aarch64_linux_hotspot_2021-05-06-23-30.tar.gz'; ;; *) echo >&2 "error: unsupported architecture: '$arch'"; exit 1 ;; esac; wget --progress=dot:giga -O openjdk.tgz "$downloadUrl"; mkdir -p ${JAVA_HOME}; tar --extract --file openjdk.tgz --directory "$JAVA_HOME" --strip-components 1 --no-same-owner ;
+# # OpenJDK 17
+# RUN arch="$(dpkg --print-architecture)"; case "$arch" in 'amd64') downloadUrl='https://github.com/AdoptOpenJDK/openjdk17-binaries/releases/download/jdk-2021-05-07-13-31/OpenJDK-jdk_x64_linux_hotspot_2021-05-06-23-30.tar.gz'; ;; 'arm64') downloadUrl='https://github.com/AdoptOpenJDK/openjdk17-binaries/releases/download/jdk-2021-05-07-13-31/OpenJDK-jdk_aarch64_linux_hotspot_2021-05-06-23-30.tar.gz'; ;; *) echo >&2 "error: unsupported architecture: '$arch'"; exit 1 ;; esac; wget --progress=dot:giga -O openjdk.tgz "$downloadUrl"; mkdir -p ${JAVA_HOME}; tar --extract --file openjdk.tgz --directory "$JAVA_HOME" --strip-components 1 --no-same-owner ;
 
-RUN rm openjdk.tgz*
+# RUN rm openjdk.tgz*
 
 # Add Apache Ant for i2b2 data model creation
-ENV ANT_VERSION=1.9.6
+ARG ANT_VERSION=1.9.6
+ARG I2B2_TAG_NAME=1.8.1.0001
 
 RUN wget http://archive.apache.org/dist/ant/binaries/apache-ant-${ANT_VERSION}-bin.tar.gz \
     && tar xvfvz apache-ant-${ANT_VERSION}-bin.tar.gz -C /opt \
@@ -76,23 +77,25 @@ RUN wget http://archive.apache.org/dist/ant/binaries/apache-ant-${ANT_VERSION}-b
     && ln -sfn /opt/ant/bin/ant /usr/bin/ant \
     && rm apache-ant-${ANT_VERSION}-bin.tar.gz
 
-WORKDIR /app
-COPY --from=base-build --chown=app:app /app/.venv /app/.venv
-
-ARG I2B2_TAG_NAME=1.8.1.0001
-
 # Change ownership to overwrite db.properties in flow definition
-COPY --from=source-code-build --chown=app:app /app/i2b2-data-$I2B2_TAG_NAME /app/i2b2-data-$I2B2_TAG_NAME
+COPY --from=i2b2-source --chown=docker:docker /app/i2b2-data-$I2B2_TAG_NAME /app/i2b2-data-$I2B2_TAG_NAME
 RUN chown -R docker:docker /app/i2b2-data-$I2B2_TAG_NAME
 
-COPY --chown=docker:docker ./_shared_flow_utils/postgresql-42.3.1.jar ./inst/drivers/
-COPY --chown=docker:docker ./__init__.py .
+COPY --chown=docker:docker  ./__init__.py /app/
+COPY --chown=docker:docker ./_shared_flow_utils/drivers /app/inst/drivers/
 
-COPY --chown=docker:docker --chmod=711 ./_shared_flow_utils _shared_flow_utils
-COPY --chown=docker:docker --chmod=711 ./i2b2/i2b2_plugin flows/i2b2_plugin
+COPY --from=python-dependencies-build --chown=docker:docker /app/.venv /app/.venv
 
-ENV PATH="/app/.venv/bin:$PATH"
+# Application files
+COPY --chown=docker:docker --chmod=711 ./_shared_flow_utils /app/_shared_flow_utils
+COPY --chown=docker:docker --chmod=711 ./i2b2/*_plugin /app/flows/
+
+RUN chmod -R 755 /app
 
 WORKDIR /app
+
+# Place executables in the environment at the front of the path
+ENV PATH="/app/.venv/bin:$PATH"
+ENV INSTALL_SQLALCHEMY_FLAG=false
 
 USER docker
