Update flows to use renv.lock and uv.lock

diff --git a/flows/data_management/Dockerfile b/flows/data_management/Dockerfile
--- a/flows/data_management/Dockerfile
+++ b/flows/data_management/Dockerfile
@@ -1,55 +1,94 @@
-FROM python:3.12-slim
+ARG PYTHON_VERSION=3.12
 
-ARG BUILD_TYPE
+FROM python:${PYTHON_VERSION}-slim AS python-dependencies-build
+
+RUN apt-get update && \
+    apt-get install -y --no-install-recommends \
+    build-essential \
+    gcc \
+    g++ \
+    libpq-dev \
+    && apt-get clean --yes \
+    && rm -rf /var/lib/apt/{apt,dpkg,cache,log}/
+
+ENV UV_LINK_MODE=copy \
+    UV_COMPILE_BYTECODE=1 \
+    UV_PYTHON_DOWNLOADS=never
+
+COPY --from=ghcr.io/astral-sh/uv:0.8.4 /uv /uvx /bin/
+
+WORKDIR /app
+
+# Install dependencies with uv into a venv
+RUN --mount=type=cache,target=/root/.cache/uv \
+    --mount=type=bind,source=./data_management/uv.lock,target=uv.lock \
+    --mount=type=bind,source=./data_management/pyproject.toml,target=pyproject.toml \
+    uv sync --locked --no-install-project --no-editable --no-dev
+
+
+FROM python:${PYTHON_VERSION}-slim AS runtime
+
 ARG USER=docker
 ENV USER=${USER}
 ARG UID=1000
 ARG GID=1000
 RUN groupadd -g $GID ${USER}
 RUN useradd -m -d /home/${USER} -s /bin/bash -g ${USER} -u ${UID} ${USER}
-WORKDIR /app
 
-RUN apt-get update && apt-get install libpq5 libpq-dev curl wget gcc g++ -y --no-install-recommends && apt-get clean
+RUN apt-get update && \
+    apt-get install -y --no-install-recommends \
+    curl \
+    wget \
+    # openjdk-17-jdk \
+    libpq5 \
+    python3-pip \
+    && apt-get clean --yes \
+    && rm -rf /var/lib/apt/{apt,dpkg,cache,log}/
+
 
 # Set environment variables
-ENV JAVA_HOME=/usr/lib/jvm/openjdk-11
+ENV JAVA_HOME=/usr/lib/jvm/openjdk-17
 ENV PATH="$JAVA_HOME/bin::/root/.cargo/bin:$PATH"
-ENV LD_LIBRARY_PATH=/usr/lib/jvm/openjdk-11/lib/server
+ENV LD_LIBRARY_PATH=/usr/lib/jvm/openjdk-17/lib/server
 
-# OpenJDK 11
-RUN arch="$(dpkg --print-architecture)"; case "$arch" in 'amd64') downloadUrl='https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.16%2B8/OpenJDK11U-jdk_x64_linux_11.0.16_8.tar.gz'; ;; 'arm64') downloadUrl='https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.16%2B8/OpenJDK11U-jdk_aarch64_linux_11.0.16_8.tar.gz'; ;; *) echo >&2 "error: unsupported architecture: '$arch'"; exit 1 ;; esac; wget --progress=dot:giga -O openjdk.tgz "$downloadUrl"; mkdir -p ${JAVA_HOME}; tar --extract --file openjdk.tgz --directory "$JAVA_HOME" --strip-components 1 --no-same-owner ;
+# OpenJDK 17
+RUN arch="$(dpkg --print-architecture)" && \
+    case "$arch" in \
+      'amd64') downloadUrl='https://github.com/AdoptOpenJDK/openjdk17-binaries/releases/download/jdk-2021-05-07-13-31/OpenJDK-jdk_x64_linux_hotspot_2021-05-06-23-30.tar.gz' ;; \
+      'arm64') downloadUrl='https://github.com/AdoptOpenJDK/openjdk17-binaries/releases/download/jdk-2021-05-07-13-31/OpenJDK-jdk_aarch64_linux_hotspot_2021-05-06-23-30.tar.gz' ;; \
+      *) echo >&2 "error: unsupported architecture: '$arch'"; exit 1 ;; \
+    esac && \
+    wget --progress=dot:giga -O openjdk.tgz "$downloadUrl" && \
+    mkdir -p ${JAVA_HOME} && \
+    tar --extract --file openjdk.tgz --directory "$JAVA_HOME" --strip-components 1 --no-same-owner && \
+    rm openjdk.tgz* && \
+    java --version
 
-RUN update-alternatives --install /usr/bin/java java ${JAVA_HOME}/bin/java 100 && \
-    update-alternatives --install /usr/bin/javac javac ${JAVA_HOME}/bin/javac 100 && \
-    rm openjdk.tgz*
+WORKDIR /app
+ADD https://github.com/liquibase/liquibase/releases/download/v4.5.0/liquibase-4.5.0.tar.gz .
+RUN mkdir -p ./liquibase/ \
+    && tar xvf liquibase-4.5.0.tar.gz -C ./liquibase/ \
+    && rm liquibase-4.5.0.tar.gz \
+    && chown -R docker:docker ./liquibase/
 
-# Verify the installation
-RUN java -version
-
+WORKDIR /app
 COPY --chown=docker:docker  ./__init__.py /app/
 COPY --chown=docker:docker ./drivers /app/inst/drivers/
 
-ADD https://github.com/liquibase/liquibase/releases/download/v4.5.0/liquibase-4.5.0.tar.gz .
-RUN mkdir -p ./liquibase/
-RUN tar xvf liquibase-4.5.0.tar.gz -C ./liquibase/
+# Copy the Python virtual environment and uv binary from the build stage
+COPY --from=python-dependencies-build --chown=docker:docker /bin/uv /usr/local/bin/uv
+COPY --from=python-dependencies-build --chown=docker:docker /app/.venv /app/.venv
 
-# Grant docker ownership to create properties file
-RUN chown -R docker:docker ./liquibase/
+# Application files
+COPY --chown=docker:docker --chmod=711 ./_shared_flow_utils /app/_shared_flow_utils
+COPY --chown=docker:docker --chmod=711 ./data_management/data_management_plugin /app/flows/data_management_plugin
 
-RUN mkdir /output
-RUN chown -R docker:docker /output
-
-COPY --chown=docker:docker --chmod=711 ./data_management/requirements_data_management.txt .
-ENV RUN_TYPE=$BUILD_TYPE
-RUN if [ $BUILD_TYPE = 'OSS' ]; then sed -i '/sqlalchemy-hana/d' /app/requirements*.txt; fi
-RUN pip install -r requirements_data_management.txt
-
-COPY --chown=docker:docker --chmod=711 ./_shared_flow_utils _shared_flow_utils
-COPY --chown=docker:docker --chmod=711 ./data_management flows
-
-# Grant docker user read/write access
 RUN chmod -R 755 /app
 
-ENV INSTALL_SQLALCHEMY_HANA=true
+WORKDIR /app
 
-# USER docker
+# Place executables in the environment at the front of the path
+ENV PATH="/app/.venv/bin:$PATH"
+ENV INSTALL_SQLALCHEMY_FLAG=true
+
+USER docker
