debug

diff --git a/.github/workflows/d2e-demosetup-hana.yml b/.github/workflows/d2e-demosetup-hana.yml
--- a/.github/workflows/d2e-demosetup-hana.yml
+++ b/.github/workflows/d2e-demosetup-hana.yml
@@ -15,6 +15,10 @@ on:
 env:
   VERSION: develop
   HDIPW: TestPW1234
+  HANASERVER: localhost
+  HANASERVER_INT: hana
+  HDIPORT: 39041
+  HDIUSER: SYSTEM
 
 jobs:
   pick_runner:
@@ -67,7 +71,8 @@ jobs:
         id: inithana
         run: |
           echo "HDIPW: ${HDIPW}"
-          timeout 10m bash -c "HANAPW=${HDIPW} ACCEPT_SAP_LICENSE=true DOTENV_FILE=.env ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config node ./scripts/dist/cli.js -e -v develop -n .env --hana inithana" || echo "HANA initialization timed out or failed, continuing..."
+          # timeout 10m bash -c "HANAPW=${HDIPW} ACCEPT_SAP_LICENSE=true DOTENV_FILE=.env ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config node ./scripts/dist/cli.js -e -v develop -n .env --hana inithana" || echo "HANA initialization timed out or failed, continuing..."
+          timeout 5m bash -c "HANAPW=${HDIPW} ACCEPT_SAP_LICENSE=true node ./scripts/dist/cli.js -e -v develop --env-file .env.local --hana inithana" || echo "HANA initialization timed out or failed, continuing..."
 
       - name: Check status of HANA containers
         run: |
