add sleep

diff --git a/.github/workflows/d2e-demosetup-release.yml b/.github/workflows/d2e-demosetup-release.yml
--- a/.github/workflows/d2e-demosetup-release.yml
+++ b/.github/workflows/d2e-demosetup-release.yml
@@ -64,6 +64,7 @@ jobs:
           retry_on: any
           command: |
             d2e -e start
+            sleep 240
             DC_EXIT_CODE=$?
             DOCKER_STATUS_FILE=../docker-status-${GITHUB_RUN_ID:-ghRunId}-$(date '+%Y%m%dT%H%M%S').txt | tee -a $GITHUB_ENV
             docker ps --format {{.Names}},{{.Status}} 2> /dev/null | sort | tee $DOCKER_STATUS_FILE | tee -a $GITHUB_STEP_SUMMARY
@@ -125,18 +126,18 @@ jobs:
         run: |
           echo "y" | d2e clean  
 
-      - name: Discord notification on status
-        if: success() || failure()
-        uses: tsickert/discord-webhook@v7.0.0
-        with:
-          webhook-url: ${{ secrets.DISCORD_WEBHOOK_DEVOPS }}
-          username: ${{ github.actor }}
-          content: "### Status of Installation\n
-            install: ${{ steps.install.outcome }}\n
-            init: ${{ steps.init.outcome }}\n
-            pull: ${{ steps.pull.outcome }}\n
-            start: ${{ steps.start.outcome }}\n
-            patchdemodb: ${{ steps.patchdemodb.outcome }}\n
-            setupdemo: ${{ steps.setupdemo.outcome }}\n
-            checkflow: ${{ steps.checkflow.outcome }}\n
-            stop: ${{ steps.stop.outcome }}"
+      # - name: Discord notification on status
+      #   if: success() || failure()
+      #   uses: tsickert/discord-webhook@v7.0.0
+      #   with:
+      #     webhook-url: ${{ secrets.DISCORD_WEBHOOK_DEVOPS }}
+      #     username: ${{ github.actor }}
+      #     content: "### Status of Installation\n
+      #       install: ${{ steps.install.outcome }}\n
+      #       init: ${{ steps.init.outcome }}\n
+      #       pull: ${{ steps.pull.outcome }}\n
+      #       start: ${{ steps.start.outcome }}\n
+      #       patchdemodb: ${{ steps.patchdemodb.outcome }}\n
+      #       setupdemo: ${{ steps.setupdemo.outcome }}\n
+      #       checkflow: ${{ steps.checkflow.outcome }}\n
+      #       stop: ${{ steps.stop.outcome }}"
