init hana pwd

diff --git a/.github/workflows/d2e-demosetup-hana.yml b/.github/workflows/d2e-demosetup-hana.yml
--- a/.github/workflows/d2e-demosetup-hana.yml
+++ b/.github/workflows/d2e-demosetup-hana.yml
@@ -14,6 +14,7 @@ on:
 
 env:
   VERSION: develop
+  HDIPW: TestPW1234
 
 jobs:
   pick_runner:
@@ -65,7 +66,8 @@ jobs:
         if: success() || failure()
         id: inithana
         run: |
-          timeout 15m bash -c "ACCEPT_SAP_LICENSE=true DOTENV_FILE=.env ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config node ./scripts/dist/cli.js -e -v develop -n .env --hana inithana" || echo "HANA initialization timed out or failed, continuing..."
+          echo "HDIPW: ${HDIPW}"
+          timeout 15m bash -c "HANAPW=${HDIPW} "ACCEPT_SAP_LICENSE=true DOTENV_FILE=.env ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config node ./scripts/dist/cli.js -e -v develop -n .env --hana inithana" || echo "HANA initialization timed out or failed, continuing..."
 
       - uses: dorny/paths-filter@v3
         id: flow_file_changes
