fix gha and env flag

diff --git a/.github/workflows/d2e-demosetup-hana.yml b/.github/workflows/d2e-demosetup-hana.yml
--- a/.github/workflows/d2e-demosetup-hana.yml
+++ b/.github/workflows/d2e-demosetup-hana.yml
@@ -57,7 +57,7 @@ jobs:
         if: success() || failure()
         id: init
         run: |
-          ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config node ./scripts/dist/cli.js -e -v develop --env-file .env init
+          ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config node ./scripts/dist/cli.js -e -v develop -n .env init
         env:
           init_choice: y
 
@@ -65,7 +65,7 @@ jobs:
         if: success() || failure()
         id: inithana
         run: |
-          timeout 5m bash -c "ACCEPT_SAP_LICENSE=true DOTENV_FILE=.env ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config node ./scripts/dist/cli.js -e -v develop --env-file .env --hana inithana" || echo "HANA initialization timed out or failed, continuing..."
+          timeout 5m bash -c "ACCEPT_SAP_LICENSE=true DOTENV_FILE=.env ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config node ./scripts/dist/cli.js -e -v develop -n .env --hana inithana" || echo "HANA initialization timed out or failed, continuing..."
 
       - uses: dorny/paths-filter@v3
         id: flow_file_changes
