fix

diff --git a/.github/workflows/functions-http-tests.yml b/.github/workflows/functions-http-tests.yml
--- a/.github/workflows/functions-http-tests.yml
+++ b/.github/workflows/functions-http-tests.yml
@@ -56,6 +56,7 @@ jobs:
       PROJECT_NAME: alp
       CADDY__CONFIG: ./deploy/caddy-config
       ENV_TYPE: local
+      DOTENV_FILE: .env.local
 
     steps:
       - uses: actions/checkout@v4
@@ -92,12 +93,17 @@ jobs:
         if: success() || failure()
         id: inithana
         run: |
-          timeout 5m bash -c "HANAPW=${HDIPW} ACCEPT_SAP_LICENSE=true DOTENV_FILE=.env.local ./scripts/cli.sh -e -v develop --env-file .env.local --hana inithana" || echo "HANA initialization timed out or failed, continuing..."
+          timeout 5m bash -c "HANAPW=${HDIPW} ACCEPT_SAP_LICENSE=true ./scripts/cli.sh -e -v develop --env-file .env.local --hana inithana" || echo "HANA initialization timed out or failed, continuing..."
 
       - name: Remove empty lines, replace ; within the query with a place holder
         run: |
           sed -i -r '/^\s*$/d' internal/build/httptest-ddl.sql
           sed -i -e 's/;,.:-/PLACE_HOLDER_STR/g' internal/build/httptest-ddl.sql
+          grep LOGTO__ALP_APP__CLIENT_ID $DOTENV_FILE | sed -e "s/'//g" >> $GITHUB_ENV
+          echo "USE_TREX_DB_CONN=false" >> $DOTENV_FILE
+          echo "USE_DUCKDB=false" >> $DOTENV_FILE
+          echo "USE_CACHEDB=false" >> $DOTENV_FILE
+          echo "NODE_ENV=production" >> $DOTENV_FILE
 
       - name: Build system services
         run: |
